### ISSUE TITLE
Kaos Engines DLC 5 and patch Azathoth 1.14 

### ISSUE THREAD

**Issue by Thyrork** [Mad-Mods-Phoenix-Point/AssortedAdjustments#24]
The following is some testing done over a few hours with the help of the console commands. Naturally other people testing will help narrow down this list more.

Working
  "DisableRocksAtBases": true,
  "EnableScrapAircraft": true,
  "DisableRightClickMove": true,
  "EnableExtendedAgendaTracker": true,
  "AgendaTrackerShowVehicles": true,
  "ShowDetailedResearchAndProduction": true,
  "AgendaTrackerAddMissionObjective": true,
  "ShowRecruitInfoInsideZoneTooltip": true,
  "ShowExtendedBaseInfo": true,
  "ShowExtendedHavenInfo": true,
  "PersistentClassFilter": true,
  "EnableLimitedWar": true,
  "LimitFactionAttacksToZones": true,
  "EnableCustomRecruitGeneration": true,
  "RecruitGenerationCount": 3,
  "IgnoreRngFactorsForHavenRecruitGeneration": true,
  "RecruitIntervalCheckDays": 3.0,
  "RecruitGenerationHasArmor": true,
  "RecruitGenerationHasWeapons": true,
  "RecruitGenerationHasConsumableItems": true,
  "RecruitGenerationHasInventoryItems": true,
  "EnableDifficultyOverrides": true,
  "DifficultyOverrideStartingSupplies": 2000.0,
  "DifficultyOverrideStartingMaterials": 4000.0,
  "DifficultyOverrideStartingTech": 1000.0,
  "DifficultyOverrideSoldierSkillPointsPerMission": 12,
  "DifficultyOverrideExpConvertedToSkillpoints": 0.02,
  "DifficultyOverrideMinPopulationThreshold": 5,
  "DifficultyOverrideStarvationDeathsPart": 0.01,
  "DifficultyOverrideStarvationMistDeathsPart": 0.03,
  "DifficultyOverrideStarvationDeathsFlat": 5,
  "DifficultyOverrideStarvationMistDeathsFlat": 15,
  "DifficultyOverrideDisableDeathByStarvation": false,
  "DifficultyOverrideMistExpansionRate": 30,
  "EmphasizeReturnFireHint": true,
  "MaxPlayerUnitsAdd": 2,
  "SkipIntroLogos": true,
  "SkipIntroMovie": true,
  "SkipLandingSequences": true,
  "EnableFacilityAdjustments": true,
  "MedicalBayBaseHeal": 8.0,
  "LivingQuartersBaseStaminaHeal": 4.0,
  "VehicleBayAircraftHealAmount": 60,
  "VehicleBayVehicleHealAmount": 40,
  "MutationLabMutogHealAmount": 40,
  "TrainingFacilityBaseExperienceAmount": 2,
  "TrainingFacilitiesGenerateSkillpoints": true,
  "TrainingFacilityBaseSkillPointsAmount": 2,
  "FabricationPlantGenerateProductionAmount": 4.0,
  "ResearchLabGenerateResearchAmount": 4.0,
  "FoodProductionGenerateSuppliesAmount": 2,
  "BionicsLabGenerateResearchAmount": 4.0,
  "MutationLabGenerateMutagenAmount": 8.0,
  "FabricationPlantGenerateMaterialsAmount": 32.0,
  "ResearchLabGenerateTechAmount": 8.0,
  "EnableSoldierAdjustments": true,
  "MaxAugmentations": 3,
  "PersonalAbilitiesCount": 5,
  "MaxStrength": 35,
  "MaxWill": 20,
  "MaxSpeed": 20,
  "Stamina": 50,
  "TiredStatusStaminaBelow": 30,
  "ExhaustedStatusStaminaBelow": 10,  
  "EnableAbilityAdjustments": true,
  "EnableVehicleAdjustments": true,
  "AircraftBlimpSpeed": 300.0,
  "AircraftThunderbirdSpeed": 400.0,
  "AircraftManticoreSpeed": 550.0,
  "AircraftHeliosSpeed": 700.0,
  "AircraftBlimpSpace": 10,
  "AircraftThunderbirdSpace": 8,
  "AircraftManticoreSpace": 10,
  "AircraftHeliosSpace": 6,
  "AircraftBlimpRange": 4000.0,
  "AircraftThunderbirdRange": 3000.0,
  "AircraftManticoreRange": 2500.0,
  "AircraftHeliosRange": 3500.0,
  "OccupyingSpaceArmadillo": 1,
  "OccupyingSpaceScarab": 1,
  "OccupyingSpaceAspida": 1,
  "PauseOnDestinationSet": true,
  "PauseOnRecruitsGenerated": true,
  "PauseOnHealed": true,

---
unsure
  "EnableSmartEvacuation": true,
  "EnableSmartBaseSelection": true,
  "AgendaTrackerShowExcavations": true,
  "AgendaTrackerShowBaseDefenses": true,
  "AgendaTrackerHideStatusBar": false,
  "EnableUIEnhancements": true,
  "PersistentClassFilterInitDisabled": false,
  "HideSiteAddons": false,
  "CompressPopulationBar": true,
  "HidePopulationBar": false,
  "BetterObjectives": true,
  "LimitPandoranAttacksToZones": false,
  "AttacksRaiseHavenAlertness": true,
  "AttacksRaiseFactionAlertness": true,
  "StopOneSidedWar": true,
  "DisablePandoranAttacksOnPhoenixBases": false,
  "StopAttacksWhileDefendingPandoransThreshold": 1,
  "GlobalAttackLimit": 3,
  "FactionAttackLimit": 2,
  "UseDifficultyDrivenLimits": false,
  "RecruitGenerationCanHaveAugmentations": false,
  "EnhanceSpecialRecruits": false,
  "EnableExperienceToSkillpointConversion": true,
  "XPtoSPAddToPersonalPool": false,
  "XPtoSPAddToFactionPool": true,
  "XPtoSPConversionMultiplier": 2.0,
  "EnableReturnFireAdjustments": true,
  "ReturnFireAngle": 180,
  "ReturnFireLimit": 2,
  "NoReturnFireWhenSteppingOut": true,
  "EnableMissionAdjustments": true,
  "AlwaysRecoverAllItemsFromTacticalMissions": false,
  "EnablePlentifulItemDrops": true,
  "ItemDestructionChance": 10,
  "AllowWeaponDrops": true,
  "FlatWeaponDestructionChance": 30,
  "HealthBasedWeaponDestruction": true,
  "AllowArmorDrops": true,
  "FlatArmorDestructionChance": 70,
  "FastMetabolism": true,
  "EnableItemAdjustments": true,
  "AmmoArmadillo": 96,
  "AmmoScarab": 16,
  "AmmoAspida": 18,
  "EnableEconomyAdjustments": true,
  "ResourceMultiplier": 0.75,
  "ScrapMultiplier": 0.5,
  "CostMultiplier": 0.5,
  "DisableAmbushes": true,
  "RetainAmbushesInsideMist": true,
  "DisableNothingFound": true,
  "OccupyingSpaceMutog": 1,
  "PauseOnExplorationSet": false,
  "CenterOnHavenRevealed": true,
  "CenterOnExcavationComplete": true,
  "Debug": true,
  "DebugDevKey": "",
  "PresetStateHash": -1

---
not working
  "UnlockItemsByResearch": true,
  "UnlockPhoenixEliteGear": true,
  "UnlockLivingWeapons": true,
  "UnlockLivingArmor": true,
  "UnlockIndependentAmmunition": false,
  "UnlockIndependentWeapons": false,
  "UnlockIndependentArmor": false,

---

**Comment by Thyrork** [comment]
Apologies for laying it out kinda poorly.

**Comment by jarnomikkola1** [comment]
These:
"UnlockIndependentAmmunition": false,
"UnlockIndependentWeapons": false,
"UnlockIndependentArmor": false,

Are also all unnessasary.

Ouh, yeah, this: 
"AmmoArmadillo": 96, 
WORKS, for the default gun it has.

**Comment by Vasenatr** [comment]
Ребят, а мод жив? Очень жду, что бы дали настройку обвесов танков гнойного неба... И сделали урон в сек менее имбовым, хотя не уверен, что оно нужно...

**Comment by jarnomikkola1** [comment]
> 

Using google translate... 
English: The mod doesn't need to be alive, it works even without been updated for a while. And I for one have not seen any errors.
Russian: Моду не обязательно быть живым, он работает даже без обновлений какое-то время. И я, например, не видел никаких ошибок.

**Comment by Vasenatr** [comment]
> > 
> 
> Using google translate... English: The mod doesn't need to be alive, it works even without been updated for a while. And I for one have not seen any errors. Russian: Моду не обязательно быть живым, он работает даже без обновлений какое-то время. И я, например, не видел никаких ошибок.

Я знаю, что он работает, но мне не хватает настройки обвеса танков из ДЛС и хотелось бы обнову по данному поводу.

**Comment by sid44sid** [comment]
У меня не работает. :(

`System.IO.FileLoadException: Could not load file or assembly 'file:///C:\Users\SID\Documents\My Games\Phoenix Point\Mods\Modnix.exe' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)
File name: 'file:///C:\Users\SID\Documents\My Games\Phoenix Point\Mods\Modnix.exe' ---> System.NotSupportedException: An attempt was made to load an assembly from a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. This release of the .NET Framework does not enable CAS policy by default, so this load may be dangerous. If this load is not intended to sandbox the assembly, please enable the loadFromRemoteSources switch. See http://go.microsoft.com/fwlink/?LinkId=155569 for more information.

   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile, Evidence securityEvidence)
   at System.Activator.CreateInstanceFromInternal(String assemblyFile, String typeName, Boolean ignoreCase, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, Evidence securityInfo)
   at System.AppDomain.CreateInstanceFrom(String assemblyFile, String typeName)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName)
   at System.AppDomain.CreateInstanceFromAndUnwrap(String assemblyName, String typeName)
   at Sheepy.Modnix.MainGUI.Sandbox.CreateSandbox()
`
![image](https://user-images.githubusercontent.com/77569802/179388111-3b2f8f0d-609b-496c-aa69-637536e9460b.png)

**Comment by jarnomikkola1** [comment]
> ` a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework. 

You clearly don't have a configuration file( AssortedAdjustments.conf ) for the mod, and your computer cannot export it from the .dll file for the above quoted reason. You just need a to make a new text file(.txt) that you rename as the "AssortedAdjustments.conf" removing the .txt extension, copy the file into the Mods/AssortedAdjustment -folder, and then copy paste this text into it, this is the default settings:

{
  "BalancePresetId": "",
  "BalancePresetState": "",
  "DisableRightClickMove": true,
  "DisableRocksAtBases": true,
  "EnableSmartEvacuation": true,
  "EnableSmartBaseSelection": true,
  "EnableScrapAircraft": true,
  "EnableExtendedAgendaTracker": true,
  "AgendaTrackerShowVehicles": true,
  "AgendaTrackerShowExcavations": true,
  "AgendaTrackerShowBaseDefenses": true,
  "AgendaTrackerHideStatusBar": false,
  "AgendaTrackerAddMissionObjective": true,
  "EnableUIEnhancements": true,
  "ShowDetailedResearchAndProduction": true,
  "ShowRecruitInfoInsideZoneTooltip": true,
  "ShowExtendedBaseInfo": true,
  "ShowExtendedHavenInfo": true,
  "PersistentClassFilter": true,
  "PersistentClassFilterInitDisabled": false,
  "HideSiteAddons": false,
  "CompressPopulationBar": true,
  "HidePopulationBar": false,
  "BetterObjectives": true,
  "EnableLimitedWar": true,
  "LimitFactionAttacksToZones": true,
  "LimitPandoranAttacksToZones": false,
  "AttacksRaiseHavenAlertness": true,
  "AttacksRaiseFactionAlertness": true,
  "StopOneSidedWar": true,
  "DisablePandoranAttacksOnPhoenixBases": false,
  "StopAttacksWhileDefendingPandoransThreshold": 1,
  "GlobalAttackLimit": 3,
  "FactionAttackLimit": 2,
  "UseDifficultyDrivenLimits": false,
  "UnlockItemsByResearch": true,
  "UnlockPhoenixEliteGear": true,
  "UnlockLivingWeapons": false,
  "UnlockLivingArmor": false,
  "UnlockIndependentAmmunition": true,
  "UnlockIndependentWeapons": false,
  "UnlockIndependentArmor": false,
  "EnableCustomRecruitGeneration": true,
  "RecruitGenerationCount": 3,
  "IgnoreRngFactorsForHavenRecruitGeneration": true,
  "RecruitIntervalCheckDays": 3.0,
  "RecruitGenerationHasArmor": true,
  "RecruitGenerationHasWeapons": true,
  "RecruitGenerationHasConsumableItems": true,
  "RecruitGenerationHasInventoryItems": true,
  "RecruitGenerationCanHaveAugmentations": false,
  "EnhanceSpecialRecruits": false,
  "EnableDifficultyOverrides": true,
  "DifficultyOverrideStartingSupplies": 800.0,
  "DifficultyOverrideStartingMaterials": 1000.0,
  "DifficultyOverrideStartingTech": 200.0,
  "DifficultyOverrideSoldierSkillPointsPerMission": 12,
  "DifficultyOverrideExpConvertedToSkillpoints": 0.02,
  "DifficultyOverrideMinPopulationThreshold": 5,
  "DifficultyOverrideStarvationDeathsPart": 0.01,
  "DifficultyOverrideStarvationMistDeathsPart": 0.03,
  "DifficultyOverrideStarvationDeathsFlat": 5,
  "DifficultyOverrideStarvationMistDeathsFlat": 15,
  "DifficultyOverrideDisableDeathByStarvation": false,
  "DifficultyOverrideMistExpansionRate": 30,
  "EnableExperienceToSkillpointConversion": true,
  "XPtoSPAddToPersonalPool": false,
  "XPtoSPAddToFactionPool": true,
  "XPtoSPConversionMultiplier": 2.0,
  "EnableReturnFireAdjustments": true,
  "ReturnFireAngle": 180,
  "ReturnFireLimit": 2,
  "NoReturnFireWhenSteppingOut": true,
  "EmphasizeReturnFireHint": true,
  "EnableMissionAdjustments": true,
  "MaxPlayerUnitsAdd": 2,
  "AlwaysRecoverAllItemsFromTacticalMissions": false,
  "EnablePlentifulItemDrops": true,
  "ItemDestructionChance": 10,
  "AllowWeaponDrops": true,
  "FlatWeaponDestructionChance": 30,
  "HealthBasedWeaponDestruction": true,
  "AllowArmorDrops": true,
  "FlatArmorDestructionChance": 70,
  "SkipIntroLogos": true,
  "SkipIntroMovie": true,
  "SkipLandingSequences": true,
  "EnableFacilityAdjustments": true,
  "MedicalBayBaseHeal": 8.0,
  "LivingQuartersBaseStaminaHeal": 4.0,
  "VehicleBayAircraftHealAmount": 60,
  "VehicleBayVehicleHealAmount": 40,
  "MutationLabMutogHealAmount": 40,
  "TrainingFacilityBaseExperienceAmount": 2,
  "TrainingFacilitiesGenerateSkillpoints": true,
  "TrainingFacilityBaseSkillPointsAmount": 1,
  "FabricationPlantGenerateProductionAmount": 4.0,
  "ResearchLabGenerateResearchAmount": 4.0,
  "FoodProductionGenerateSuppliesAmount": 0.5,
  "BionicsLabGenerateResearchAmount": 4.0,
  "MutationLabGenerateMutagenAmount": 0.25,
  "FabricationPlantGenerateMaterialsAmount": 1.0,
  "ResearchLabGenerateTechAmount": 1.0,
  "EnableSoldierAdjustments": true,
  "MaxAugmentations": 3,
  "PersonalAbilitiesCount": 5,
  "MaxStrength": 35,
  "MaxWill": 20,
  "MaxSpeed": 20,
  "Stamina": 50,
  "TiredStatusStaminaBelow": 30,
  "ExhaustedStatusStaminaBelow": 10,
  "FastMetabolism": true,
  "EnableAbilityAdjustments": false,
  "EnableItemAdjustments": false,
  "EnableVehicleAdjustments": true,
  "AircraftBlimpSpeed": 300.0,
  "AircraftThunderbirdSpeed": 400.0,
  "AircraftManticoreSpeed": 550.0,
  "AircraftHeliosSpeed": 700.0,
  "AircraftBlimpSpace": 10,
  "AircraftThunderbirdSpace": 8,
  "AircraftManticoreSpace": 7,
  "AircraftHeliosSpace": 6,
  "AircraftBlimpRange": 4000.0,
  "AircraftThunderbirdRange": 3000.0,
  "AircraftManticoreRange": 2500.0,
  "AircraftHeliosRange": 3500.0,
  "OccupyingSpaceMutog": 2,
  "OccupyingSpaceArmadillo": 2,
  "OccupyingSpaceScarab": 2,
  "OccupyingSpaceAspida": 2,
  "AmmoArmadillo": 96,
  "AmmoScarab": 16,
  "AmmoAspida": 18,
  "EnableEconomyAdjustments": true,
  "ResourceMultiplier": 0.75,
  "ScrapMultiplier": 0.5,
  "CostMultiplier": 0.5,
  "DisableAmbushes": true,
  "RetainAmbushesInsideMist": true,
  "DisableNothingFound": true,
  "PauseOnDestinationSet": true,
  "PauseOnExplorationSet": false,
  "PauseOnRecruitsGenerated": true,
  "PauseOnHealed": true,
  "CenterOnHavenRevealed": true,
  "CenterOnExcavationComplete": true,
  "Debug": true,
  "DebugDevKey": "",
  "PresetStateHash": -1
}

**Comment by sid44sid** [comment]
> > ` a network location which would have caused the assembly to be sandboxed in previous versions of the .NET Framework.
> 
> You clearly don't have a configuration file( AssortedAdjustments.conf ) for the mod, and your computer cannot export it from the .dll file for the above quoted reason. You just need a to make a new text file(.txt) that you rename as the "AssortedAdjustments.conf" removing the .txt extension, copy the file into the Mods/AssortedAdjustment -folder, and then copy paste this text into it, this is the default settings:
> 
> 

This worked like a charm! Thank you so much!
